# VECTORS

In [5]:
# Creating vector
price_list=[10,5,8,8,3,3,20,6]
import numpy as np
#np.array(10,5,8,8,3,3,20,6)
np.array(price_list) # converting list to vector

array([10,  5,  8,  8,  3,  3, 20,  6])

In [6]:
price_list=[50,80,40,30]#[p1,p2,p3,p4]
quantity_list=[2,5,6,3]#[q1,q2,q3,q4]
price_vec=np.array(price_list)
quantity_vec=np.array(quantity_list)
#taking dot product of two sectors=p1q1+p2q2+p3q3+p4q4
total_expenditure=np.dot(price_vec,quantity_vec)
print("total expenditure:",total_expenditure)

total expenditure: 830


In [11]:
#a1 x1 +a2 x2=b........(i)
# [a1 a2][x1 x2]'=[b]
#b1 x1 +b2 x2=c........(ii)
import numpy as np
A=np.array([['a1','a2'],['b1','b2']])
X=np.array(["x1","x2"])
c=np.array(["b","c"])
print("matrix A \n",A)
print("variable matrix X :, \n",X.T)
print("coeffient matrix X c: \n",c.T)
#The above liner equations (i)&(ii) can be represented in the following form
#AX=C
#X=inverse(A)xC
#inverse(A)=Adj(A)/det(A)

matrix A 
 [['a1' 'a2']
 ['b1' 'b2']]
variable matrix X :, 
 ['x1' 'x2']
coeffient matrix X c: 
 ['b' 'c']


## Finding dimentions of a matrix

In [12]:
A.shape

(2, 2)

## Matrix operations

In [13]:
#creation to matrix A&B of 2X2
A=np.array([[2,4],[5,9]])
B=np.array([[15,1],[24,19]])
print("matrix A:\n",A)
print("matrix B:\n",B)

matrix A:
 [[2 4]
 [5 9]]
matrix B:
 [[15  1]
 [24 19]]


In [15]:
#Matrix Addition
print("Addition of matrices A,B \n", A+B)
#Matrix substraction
print("substraction of matrices A&B \n, A-B")
#Matrix multipilcation
# A*B means element_wise multiplication.
# A@B means matrix multiplication.
print("multiplication of two matrices A,B using np.matmul()fn \n",np.matmul(A,B))
print("multiplication of two matrices A,B using A@B\n",A@B)

Addition of matrices A,B 
 [[17  5]
 [29 28]]
substraction of matrices A&B 
, A-B
multiplication of two matrices A,B using np.matmul()fn 
 [[126  78]
 [291 176]]
multiplication of two matrices A,B using A@B
 [[126  78]
 [291 176]]


In [16]:
# Identity Matrix
np.eye(2)#2x2 Identity Matrix

array([[1., 0.],
       [0., 1.]])

In [17]:
np.eye(3)#3x3`

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Matrices-Transpose and inverse

In [18]:
#Transpose of matrix A
print("matrix A \n",A)
print("Transpose of A \n",A.T)
print("Transpose of A using np.Transpose() \n",np.transpose(A))

matrix A 
 [[2 4]
 [5 9]]
Transpose of A 
 [[2 5]
 [4 9]]
Transpose of A using np.Transpose() 
 [[2 5]
 [4 9]]


In [21]:
np.transpose(A)

array([[2, 5],
       [4, 9]])

In [22]:
# Inverse of a matrix
print("matrix A \n",A)
print("Inverse of A \n",np.linalg.inv(A))

matrix A 
 [[2 4]
 [5 9]]
Inverse of A 
 [[-4.5  2. ]
 [ 2.5 -1. ]]


In [24]:
# Calculating determinant of A
#A= [[a1,a2],[b1,b2]]
#determinent of A =a1b2-a2b1
import numpy as np
print(A)
print("determinent of A:",np.linalg.det(A))

[[2 4]
 [5 9]]
determinent of A: -1.999999999999999


## Linear equations

In [31]:
# Solving a 2-market equilibrium system:
#3P1+2P2=18 (Market 1 equilibrium)
#1P1+4P2=16 (Market 2 eQuilibrium)
#the above linear equations can be written in the following matrix form.
#AX=b
#X = A_inverse.b
# Coefficient Matrix (A)and constants vector(b)
A=np.array([[3,2],[1,4]])
b=np.array([18,16])
X=np.linalg.solve(A,b)

In [32]:
P1=X[0]
P2=X[1]
print(P1,P2)

4.0 3.0


In [33]:
#Method 1:Direct solver
X=np.linalg.solve(A,b)
print("Equilibrium price vectors:",X)
#Method 2:Matrix inversion (X=A^-1*b)
X_inv=np.linalg.inv(A) @ b
print(f"Equilibrium price P1:{X[0]:2f}")
print(f"Equilibrium price P2:{X[1]:2f}")

Equilibrium price vectors: [4. 3.]
Equilibrium price P1:4.000000
Equilibrium price P2:3.000000


## Eigen Values and Eigen Vectors

In [38]:
M=np.array([[0.9,0.8],[0.2,0.8]])
eigenvalues,eigenvectors=np.linalg.eig(M)
#eigenvalues
print("Eigen values:",eigenvalues)
print("Eigen vectors:",eigenvalues)

Eigen values: [1.25311289 0.44688711]
Eigen vectors: [1.25311289 0.44688711]
